# Generated by Django 6.1 on 2026-08-19 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('modalidad', models.CharField(choices=[('Remoto', 'Remoto'), ('Presencial', 'Presencial'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('salario_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salario_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salario_moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('salario_periodo', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10, null=True)),
                ('requisitos', models.JSONField(default=list)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('experiencia', models.JSONField(blank=True, null=True)),
                ('educacion', models.JSONField(blank=True, null=True)),
                ('habilidades', models.JSONField(blank=True, default=list)),
                ('campos_pendientes', models.JSONField(blank=True, default=list)),
                ('cv_nombre_archivo', models.CharField(max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
