# Generated by Django 6.1 on 2026-10-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='exp_disponibilidad',
            field=models.CharField(blank=True, choices=[('inmediata', 'Inmediata'), ('dos_semanas', '2 semanas'), ('un_mes', '1 mes')], max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='exp_modalidad',
            field=models.CharField(blank=True, choices=[('Remoto', 'Remoto'), ('Presencial', 'Presencial'), ('Híbrido', 'Híbrido')], max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='exp_salario_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='exp_ubicacion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
