# Generated by Django 6.1 on 2026-10-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_perfil_exp_disponibilidad_perfil_exp_modalidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('coincidencias', models.JSONField(default=list)),
                ('fecha', models.DateField()),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_diarios', to='vacantes.perfil')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacante')),
            ],
            options={
                'ordering': ['-fecha', '-score'],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'vacante', 'fecha'), name='unico_match_por_dia')],
            },
        ),
    ]
