# Generated by Django 6.1 on 2026-10-04 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_matchdiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('postulado', 'Postulado'), ('en_revision', 'En revisión'), ('entrevista', 'Entrevista'), ('descartado', 'Descartado')], default='postulado', max_length=20)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='vacantes.perfil')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['-fecha_aplicacion'],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'vacante'), name='una_postulacion_por_vacante')],
            },
        ),
    ]
