# Generated by Django 6.1 on 2026-10-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0004_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='anios_experiencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='experiencia_minima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExplicacionCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('habilidades', 'Habilidades'), ('experiencia', 'Experiencia'), ('salario', 'Salario'), ('modalidad', 'Modalidad'), ('ubicacion', 'Ubicación')], max_length=20)),
                ('score_pct', models.FloatField()),
                ('texto', models.TextField()),
                ('generado_en', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicaciones', to='vacantes.perfil')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicaciones', to='vacantes.vacante')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('perfil', 'vacante', 'criterio'), name='una_explicacion_por_criterio')],
            },
        ),
    ]
