# Generated by Django 6.1 on 2026-10-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0005_perfil_anios_experiencia_vacante_experiencia_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
