# Generated by Django 6.1 on 2026-10-06 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0006_vacante_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='canal_notificacion',
            field=models.CharField(choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_pct', models.PositiveIntegerField()),
                ('mensaje', models.CharField(max_length=255)),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('enviada', models.BooleanField(default=False)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='vacantes.perfil')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['-creada_en'],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'vacante', 'fecha'), name='una_notificacion_por_match_por_dia')],
            },
        ),
    ]
