# Generated by Django 6.1 on 2026-10-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0007_perfil_canal_notificacion_perfil_telefono_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['perfil', 'leida'], name='vacantes_no_perfil__b71245_idx'),
        ),
    ]
