# Generated by Django 6.1 on 2026-10-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0008_notificacion_vacantes_no_perfil__b71245_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='canal_notificacion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
    ]
