"""
Django settings for scoutly project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1(1!@u*m7fmsfkn8d)mp0a2qa22n77%+3-n1$j0z_kiqai55&)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://*.loca.lt']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'vacantes',
]

AUTH_USER_MODEL = 'accounts.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scoutly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vacantes.context_processors.notificaciones_sin_leer',
            ],
        },
    },
]

WSGI_APPLICATION = 'scoutly.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Candidatos y vacantes son colombianos; "hoy" para Matches de hoy (HU-06)
# debe ser el día en Bogotá, no en UTC.
TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sesión: se mantiene activa 30 días, igual que el Sprint 1 original.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

LOGIN_URL = '/login'

# HU-06: token compartido que el workflow de n8n manda en el header
# X-Scoutly-Token al disparar POST /api/recalcular-matches. En desarrollo
# cae a un valor fijo (conocido, está en este repo) para que el endpoint
# funcione sin configurar nada; con DEBUG=False, views.recalcular_matches_api
# rechaza este valor en vez de aceptarlo como si fuera un secreto real —
# ver la comparación ahí.
N8N_SCORING_TOKEN_DEV_DEFAULT = 'dev-local-token-change-me'
N8N_SCORING_TOKEN = os.environ.get('N8N_SCORING_TOKEN', N8N_SCORING_TOKEN_DEV_DEFAULT)

# Explicaciones por criterio del matching (vacantes/ai_explicaciones.py),
# vía la API gratuita de Groq (console.groq.com — sin tarjeta de crédito).
# Sin esta variable, obtener_explicacion() cae directo al texto de
# respaldo (no genérico, pero sin redactar por IA) — no rompe nada.
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')

# HU-11: notificaciones de nuevos matches (vacantes/notificaciones.py).
# Único canal: correo (se evaluó WhatsApp vía Twilio y se descartó —
# exige que cada candidato haga un opt-in manual antes de poder recibir
# nada; el correo con SMTP real no le pide ningún paso extra).
#
# Por defecto usa el backend de consola de Django — el correo no sale a
# internet, se imprime en la terminal donde corre `runserver`. Eso sirve
# como evidencia para la demo (y Notificacion.enviada queda en True) sin
# configurar nada. Para que llegue de verdad a una bandeja de entrada,
# exportar antes de levantar el servidor:
#   DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST / EMAIL_PORT / EMAIL_HOST_USER / EMAIL_HOST_PASSWORD / EMAIL_USE_TLS
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'notificaciones@scoutly.local')
